### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by WCY-dt** [Unparalleled-Calvin/WallNote#1]
膜拜我崔神(❤ ω ❤)

我宣布 cch 就是神！复旦的神！我的神！

很有意思的小项目，提几个建议：

1. （强迫症）git 分支管理通常不会一个版本建一个分支，更加主流的操作可以参考 [这个](https://nvie.com/posts/a-successful-git-branching-model/)
2. （强迫症）html 里面的 script 可不可以塞进一个单独的 js 文件，强迫症看着难受（；´д｀）ゞ
3. （瞎扯）这种软件应该是走轻量级方向的（ vscode 都没你这个大），那两个调用的库可以考虑重构一下，或者至少删掉些冗余代码

**Comment by WCY-dt** [comment]
最后一条可以忽略。
**你的很大，我忍一下（划掉）**

**Comment by Unparalleled-Calvin** [comment]
非常感谢你的建议。
确实，我仅停留在会用git的阶段，但是对规范还不是很了解，我会好好看链接内容滴。
(我室友也和我讲过html的js写在一个文件里比较好)
electron这个玩意写出来的好像都很大(有个70M的内核)，我不知道那种轻量的窗口是怎么写出来的，还在网上搜了一下有没有更轻量的框架。但是就连winform也需要把框架给打包进可执行文件，所以我怀疑那些应用是用Qt或者其他更细致的东西写出来的。

**Comment by WCY-dt** [comment]
我提到的 vscode 就是用的 electron，从它的 package.json 里面就能看到（链接： #[vscode](https://github.com/microsoft/vscode/blob/main/package.json)
不过它似乎做了很多优化
haha具体我也不太清楚🌝
